# Podfile for CloudXMediationInMobiAdapter development

platform :ios, '14.0'
use_frameworks! :linkage => :static

target 'CloudXMediationInMobiAdapter' do
  pod 'CloudXCore', :path => '../core'
  pod 'InMobiSDK', '~> 10.8'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

