//
//  CLXInMobiBidTokenSource.h
//  CloudXInMobiAdapter
//
//  Created by CloudX Team.
//

#import <Foundation/Foundation.h>
#import <CloudXCore/CLXBidTokenSource.h>

NS_ASSUME_NONNULL_BEGIN

/**
 * InMobi bid token source for CloudX header bidding integration.
 * 
 * The bid token is a cryptographically signed payload generated by InMobi's SDK that contains:
 * - User targeting data (demographic, behavioral, interest signals)
 * - Device information (IDFA, device type, OS version, screen size)
 * - App context (bundle ID, app category, user engagement metrics)
 * - Privacy-compliant user identifiers and consent status
 * - Real-time bidding signals for ad auction optimization
 */
@interface CLXInMobiBidTokenSource : NSObject <CLXBidTokenSource>

/**
 * Shared instance for InMobi bid token source.
 * @return Singleton instance
 */
+ (instancetype)sharedInstance;

/**
 * Factory method for CloudX adapter resolution system.
 * @return New instance of InMobi bid token source
 */
+ (instancetype)createInstance;

@end

NS_ASSUME_NONNULL_END

