platform :ios, '15.0'

target 'CloudXObjCRemotePods' do
  use_frameworks! :linkage => :static

  # CloudX SDK - Source development
  pod 'CloudXCore', :path => '../core'
  pod 'CloudXMetaAdapter', :path => '../adapter-meta'
  pod 'CloudXVungleAdapter', :path => '../adapter-vungle'
  pod 'CloudXInMobiAdapter', :path => '../adapter-inmobi'
  pod 'CloudXRenderer', :path => '../renderer-cloudx'

  target 'CloudXObjCRemotePodsTests' do
    inherit! :search_paths
  end

  target 'CloudXObjCRemotePodsUITests' do
  end

end
