platform :ios, '15.0'

target 'CloudXObjCRemotePods' do
  use_frameworks! :linkage => :static

  # Testing v1.2.0 from release branch
  pod 'CloudXCore', :git => 'https://github.com/cloudx-io/cloudx-ios.git', :branch => 'release/v1.2.0'
  pod 'CloudXMetaAdapter', :git => 'https://github.com/cloudx-io/cloudx-ios.git', :branch => 'release/v1.2.0'
  pod 'CloudXRenderer', :git => 'https://github.com/cloudx-io/cloudx-ios.git', :branch => 'release/v1.2.0'
  pod 'CloudXVungleAdapter', :git => 'https://github.com/cloudx-io/cloudx-ios.git', :branch => 'release/v1.2.0'

  target 'CloudXObjCRemotePodsTests' do
    inherit! :search_paths
  end

  target 'CloudXObjCRemotePodsUITests' do
  end
end
