# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloudXMintegralAdapter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloudXMintegralAdapter
  pod 'MintegralAdSDK/BidNativeAd'
  pod 'MintegralAdSDK/BidRewardVideoAd'
  pod 'MintegralAdSDK/BidNewInterstitialAd'
  pod 'MintegralAdSDK/BidBannerAd'
  pod 'MintegralAdSDK/BidNativeAdvancedAd'
  pod 'CloudXCore'

  target 'CloudXMintegralAdapterTests' do
    # Pods for testing
  end

end
