# Podfile for CloudXMintegralAdapter development

platform :ios, '13.0'
use_frameworks! :linkage => :static

target 'CloudXMintegralAdapter' do
  pod 'CloudXCore', :path => '../core'
  pod 'MintegralAdSDK/BidBannerAd', '~> 8.0'
  pod 'MintegralAdSDK/BidNewInterstitialAd', '~> 8.0'
  pod 'MintegralAdSDK/BidRewardVideoAd', '~> 8.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
