# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'CloudXMetaAdapter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloudXMetaAdapter
  pod 'FBAudienceNetwork', '6.16.0'
  pod 'CloudXCore', '1.1.41'

  target 'CloudXMetaAdapterTests' do
    # Pods for testing
  end

end
