# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloudXDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'CloudXCore', :git => 'https://github.com/cloudx-xenoss/cloudexchange.sdk.ios.core', :branch => 'objc-support-only-forcloudX-methods'
   pod 'CloudXDSPAdapter', :git => 'https://github.com/cloudx-xenoss/cloudexchange.sdk.ios.cloudXDSPAdapter', :branch => 'develop'
   pod 'CloudXDemoAdapter', :git => 'https://github.com/cloudx-xenoss/cloudexchange.sdk.ios.testAdapter', :branch => 'updated-swift-version'
  target 'CloudXDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CloudXDemoUITests' do
    # Pods for testing
  end

end
