#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

// MARK: - ConfigProperty
typedef NSString * const RillImpressionConfigProperty NS_TYPED_ENUM;
FOUNDATION_EXPORT RillImpressionConfigProperty const RillImpressionConfigPropertyMetricsEndpointURL;
FOUNDATION_EXPORT RillImpressionConfigProperty const RillImpressionConfigPropertySessionID;
FOUNDATION_EXPORT RillImpressionConfigProperty const RillImpressionConfigPropertyPreCacheSize;
FOUNDATION_EXPORT RillImpressionConfigProperty const RillImpressionConfigPropertyEventTrackingURL;
FOUNDATION_EXPORT RillImpressionConfigProperty const RillImpressionConfigPropertyCur;
FOUNDATION_EXPORT RillImpressionConfigProperty const RillImpressionConfigPropertyId;
FOUNDATION_EXPORT RillImpressionConfigProperty const RillImpressionConfigPropertyBidid;
FOUNDATION_EXPORT RillImpressionConfigProperty const RillImpressionConfigPropertyImpressionTrackerURL;
FOUNDATION_EXPORT RillImpressionConfigProperty const RillImpressionConfigPropertyOrganizationID;
FOUNDATION_EXPORT RillImpressionConfigProperty const RillImpressionConfigPropertyAccountID;

// MARK: - BidProperty
typedef NSString * const RillImpressionBidProperty NS_TYPED_ENUM;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyId;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyAdm;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyAdid;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyImpid;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyBundle;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyBurl;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyAdomain;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyPrice;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyAbTestId;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyAbTestGroup;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyNurl;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyIurl;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyCat;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyCid;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyCrid;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyDealid;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyW;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyH;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtOrigbidcpm;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtOrigbidcur;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtCloudxRank;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtCloudxAdapterExtras;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtCloudxMetaAdaptercode;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnVersion;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnNetwork;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnSourceidentifier;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnCampaign;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnItunesitem;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnProductpageid;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnNonce;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnSourceapp;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnTimestamp;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnSignature;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnFidelitiesFidelity;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnFidelitiesNonce;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnFidelitiesSignature;
FOUNDATION_EXPORT RillImpressionBidProperty const RillImpressionBidPropertyExtSkadnFidelitiesTimestamp;

// MARK: - BidRequestProperty
typedef NSString * const RillImpressionBidRequestProperty NS_TYPED_ENUM;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyId;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyAppId;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyAppVer;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyAppBundle;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyExtAdapterExtrasMintegralBuyerId;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyExtPrebidAdservertargetingKey;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyExtPrebidAdservertargetingValue;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyExtPrebidAdservertargetingSource;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyRegsCoppa;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyRegsExtCcpaDoNotSell;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyRegsExtGdprConsent;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyRegsExtIabGdprTcfv2GdprApplies;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceOs;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceIfa;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceHwv;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceH;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDevicePpi;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceJs;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceLanguage;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceDnt;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceUa;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceDevicetype;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceGeoUtcoffset;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDevicePxratio;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceLmt;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceOsv;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceW;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceModel;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceConnectiontype;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyDeviceMake;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyImpId;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyImpTagid;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyImpSecure;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyImpExtPrebidStoredimpressionId;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyImpBannerFormatW;
FOUNDATION_EXPORT RillImpressionBidRequestProperty const RillImpressionBidRequestPropertyImpBannerFormatH;

NS_ASSUME_NONNULL_END 