# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'CloudXRenderer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloudXRenderer
  # LOCAL development (monorepo)
  pod 'CloudXCore', :path => '../core'

  # REMOTE development
  # pod 'CloudXCore', :podspec => 'https://raw.githubusercontent.com/cloudx-xenoss/CloudXCoreiOS/main/CloudXCore.podspec.json'
  # pod 'CloudXCore'

  target 'CloudXRendererTests' do
    # Pods for testing
  end

end 