# Podfile for CloudXVungleAdapter development

platform :ios, '12.0'
use_frameworks!

target 'CloudXVungleAdapter' do
  pod 'CloudXCore', :path => '../core'
  pod 'VungleAdsSDK', '~> 7.4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
