# Podfile for CloudXVungleAdapter development

platform :ios, '13.0'
use_frameworks! :linkage => :static

target 'CloudXVungleAdapter' do
  pod 'CloudXCore', :path => '../core'
  pod 'VungleAds', '~> 7.7.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
