#import "CLXMintegralInitializer.h"
#import <CloudXCore/CLXLogger.h>
#import <CloudXCore/CLXError.h>
#import <CloudXCore/CLXBidderConfig.h>
#import <MTGSDK/MTGSDK.h>
#import "CLXMintegralInterstitialFactory.h"
#import "CLXMintegralBannerFactory.h"
#import "CLXMintegralRewardedFactory.h"
#import "CLXMintegralBidTokenSource.h"

// CloudX Channel Code for Mintegral attribution
// This is a unique identifier assigned by Mintegral for CloudX mediation
static NSString * const kCloudXChannelCode = @"Y+H6DFttYrPQYcIAicKwJQKQYrN=";

@interface CLXMintegralInitializer ()
@property (nonatomic, strong) CLXLogger *logger;
@property (nonatomic, assign) BOOL initialized;
@end

@implementation CLXMintegralInitializer

static BOOL isInitialized = NO;
static NSString * const kSDKVersion = @"8.0.3"; // Mintegral SDK version (update as needed)

+ (BOOL)isInitialized {
    return isInitialized;
}

+ (instancetype)createInstance {
    return [[CLXMintegralInitializer alloc] init];
}

+ (NSString *)sdkVersion {
    NSString *version = [MTGSDK sdkVersion];
    return version ?: kSDKVersion;
}

- (instancetype)init {
    self = [super init];
    if (self) {
        _sdkVersion = [CLXMintegralInitializer sdkVersion];
        _network = @"mintegral";
        _logger = [[CLXLogger alloc] initWithCategory:@"CLXMintegralInitializer"];
    }
    return self;
}

- (void)initializeWithConfig:(nullable CLXBidderConfig *)config
                    testMode:(BOOL)testMode
                  completion:(void (^)(BOOL success, NSError * _Nullable error))completion {
    
    [self.logger debug:[NSString stringWithFormat:@"Initializing Mintegral adapter (testMode: %@)", testMode ? @"YES" : @"NO"]];
    // Note: testMode parameter received from server deviceConfig
    
    if (isInitialized) {
        [self.logger info:@"Mintegral SDK already initialized"];
        if (completion) completion(YES, nil);
        return;
    }
    
    // Extract Mintegral-specific credentials from provisioning response
    // AppLovin pattern: just use what the server provides
    NSString *appID = config.initializationData[@"appID"];
    NSString *appKey = config.initializationData[@"appKey"];
    
    if (!appID || appID.length == 0 || !appKey || appKey.length == 0) {
        NSError *error = [CLXError errorWithCode:CLXErrorCodeAdapterInvalidConfiguration
                                     description:@"Missing Mintegral App ID or App Key"];
        [self.logger error:@"Failed to initialize Mintegral: missing App ID or App Key"];
        if (completion) completion(NO, error);
        return;
    }
    
    dispatch_async(dispatch_get_main_queue(), ^{
        @try {
            MTGSDK *mtgSDK = [MTGSDK sharedInstance];
            
            // Set channel code BEFORE initialization (for attribution)
            [self setChannelCode:mtgSDK];
            
            [self.logger debug:[NSString stringWithFormat:@"Initializing Mintegral SDK with AppID: %@", appID]];
            
            // Configure privacy settings BEFORE SDK initialization
            // Note: Mintegral reads IAB TCF/USP strings from UserDefaults automatically
            [self configurePrivacySettings];
            
            // Initialize Mintegral SDK
            [mtgSDK setAppID:appID ApiKey:appKey];
            
            [self.logger info:[NSString stringWithFormat:@"Mintegral SDK initialized with version: %@", 
                             [MTGSDK sdkVersion] ?: @"unknown"]];
            
            isInitialized = YES;
            [self.logger success:@"Mintegral adapter initialized successfully"];
            
            if (completion) completion(YES, nil);
            
        } @catch (NSException *exception) {
            NSError *error = [CLXError errorWithCode:CLXErrorCodeInternalError
                                         description:exception.reason ?: @"Unknown initialization error"];
            [self.logger error:[NSString stringWithFormat:@"Mintegral initialization failed: %@", exception.reason]];
            if (completion) completion(NO, error);
        }
    });
}

/**
 * Set the channel code so that logs generated by Mintegral SDK can be attributed to CloudX.
 * This matches the pattern used by AppLovin's adapter.
 *
 * NOTE: The channel code must be obtained from Mintegral directly. Contact your Mintegral
 * account representative to request a unique channel code for CloudX.
 */
- (void)setChannelCode:(MTGSDK *)mtgSDK {
    // Skip if no channel code has been configured
    if (kCloudXChannelCode == nil || kCloudXChannelCode.length == 0) {
        [self.logger debug:@"No Mintegral channel code configured - skipping attribution setup. "
                           @"Contact Mintegral to obtain a channel code for CloudX."];
        return;
    }
    
    @try {
        Class mintegralSdkClass = [mtgSDK class];
        SEL setChannelFlagSelector = NSSelectorFromString(@"setChannelFlag:");
        
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Warc-performSelector-leaks"
        if ([mintegralSdkClass respondsToSelector:setChannelFlagSelector]) {
            [mintegralSdkClass performSelector:setChannelFlagSelector withObject:kCloudXChannelCode];
            [self.logger debug:@"Set CloudX channel code for Mintegral attribution"];
        }
#pragma clang diagnostic pop
    }
    @catch (NSException *exception) {
        [self.logger warn:[NSString stringWithFormat:@"Failed to set channel code: %@", exception.reason]];
    }
}

- (void)configurePrivacySettings {
    MTGSDK *mtgSDK = [MTGSDK sharedInstance];
    
    // GDPR Consent - Check for IAB TCF consent or explicit consent
    // Must be set BEFORE SDK initialization per Mintegral docs
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    
    // Check IAB TCF 2.0 consent (GDPR applies = 1, Purpose consent bit 1 = advertising)
    NSNumber *gdprApplies = [defaults objectForKey:@"IABTCF_gdprApplies"];
    NSString *purposeConsents = [defaults stringForKey:@"IABTCF_PurposeConsents"];
    
    if (gdprApplies != nil) {
        if ([gdprApplies integerValue] == 1) {
            // GDPR applies - check purpose consent (bit 1 is purpose 1 for advertising)
            BOOL hasAdConsent = (purposeConsents.length > 0 && [purposeConsents characterAtIndex:0] == '1');
            mtgSDK.consentStatus = hasAdConsent;
            [self.logger debug:[NSString stringWithFormat:@"GDPR applies, consent status set to: %@", hasAdConsent ? @"YES" : @"NO"]];
        } else {
            // GDPR doesn't apply - allow tracking
            mtgSDK.consentStatus = YES;
            [self.logger debug:@"GDPR doesn't apply, consent status set to YES"];
        }
    } else {
        [self.logger debug:@"No GDPR signal found, Mintegral will read IAB TCF strings from UserDefaults"];
    }
    
    // CCPA / US Privacy - Check IAB US Privacy String
    // Format: 1YNN = version, explicit notice, opt-out sale, LSPA covered
    // If character 3 is 'Y', user has opted out of sale
    NSString *usPrivacy = [defaults stringForKey:@"IABUSPrivacy_String"];
    
    if (usPrivacy.length >= 3) {
        BOOL doNotTrack = ([usPrivacy characterAtIndex:2] == 'Y');
        mtgSDK.doNotTrackStatus = doNotTrack;
        [self.logger debug:[NSString stringWithFormat:@"CCPA doNotTrack status set to: %@", doNotTrack ? @"YES" : @"NO"]];
    } else {
        [self.logger debug:@"No CCPA signal found, Mintegral will read IAB US Privacy from UserDefaults"];
    }
}

@end
