#import "CLXMintegralInitializer.h"
#import <CloudXCore/CLXLogger.h>
#import <CloudXCore/CLXError.h>
#import <CloudXCore/CLXBidderConfig.h>
#import <MTGSDK/MTGSDK.h>

// CloudX Channel Code for Mintegral attribution
// This is a unique identifier assigned by Mintegral for CloudX mediation
static NSString * const kCloudXChannelCode = @"Y+H6DFttYrPQYcIAicKwJQKQYrN=";

static NSString * const kIABUSPrivacy_String = @"IABUSPrivacy_String";

@interface CLXMintegralInitializer ()
@property (nonatomic, strong) CLXLogger *logger;
@end

@implementation CLXMintegralInitializer

static NSInteger sInitializationStatus = 0; // 0 = uninitialized, 1 = initializing, 2 = initialized

+ (BOOL)isInitialized {
    return sInitializationStatus == 2;
}

+ (instancetype)createInstance {
    return [[CLXMintegralInitializer alloc] init];
}

+ (NSString *)sdkVersion {
    return [MTGSDK sdkVersion];
}

- (instancetype)init {
    self = [super init];
    if (self) {
        _sdkVersion = [CLXMintegralInitializer sdkVersion];
        _network = @"mintegral";
        _logger = [[CLXLogger alloc] initWithCategory:@"CLXMintegralInitializer"];
    }
    return self;
}

- (void)initializeWithConfig:(nullable CLXBidderConfig *)config
                    testMode:(BOOL)testMode
                  completion:(void (^)(BOOL success, NSError * _Nullable error))completion {

    @synchronized([CLXMintegralInitializer class]) {
        [self.logger debug:[NSString stringWithFormat:@"Initializing Mintegral adapter (testMode: %@)", testMode ? @"YES" : @"NO"]];

        if (sInitializationStatus == 2) {
            [self.logger debug:@"Mintegral SDK already initialized"];
            if (completion) completion(YES, nil);
            return;
        }

        if (sInitializationStatus == 1) {
            [self.logger debug:@"Mintegral SDK initialization already in progress"];
            NSError *error = [CLXError errorWithCode:CLXErrorCodeAdapterInternalError
                                         description:@"Mintegral SDK initialization already in progress"];
            if (completion) completion(NO, error);
            return;
        }

        NSString *appID = config.initializationData[@"appID"];
        NSString *appKey = config.initializationData[@"appKey"];

        if (!appID || appID.length == 0 || !appKey || appKey.length == 0) {
            NSError *error = [CLXError errorWithCode:CLXErrorCodeAdapterInvalidConfiguration
                                         description:@"Missing Mintegral App ID or App Key"];
            [self.logger error:@"Failed to initialize Mintegral: missing App ID or App Key"];
            if (completion) completion(NO, error);
            return;
        }

        sInitializationStatus = 1;

        @try {
            MTGSDK *mtgSDK = [MTGSDK sharedInstance];

            [self setChannelCode:mtgSDK];

            // CCPA must be configured BEFORE setAppID:ApiKey:.
            // GDPR/TCF is auto-read by Mintegral from NSUserDefaults.
            [self configurePrivacySettings:mtgSDK];

            [self.logger debug:[NSString stringWithFormat:@"Initializing Mintegral SDK with AppID: %@", appID]];

            [mtgSDK setAppID:appID ApiKey:appKey];

            sInitializationStatus = 2;
            [self.logger info:[NSString stringWithFormat:@"Mintegral SDK initialized (v%@)",
                             [MTGSDK sdkVersion] ?: @"unknown"]];
            if (completion) completion(YES, nil);

        } @catch (NSException *exception) {
            [self.logger error:[NSString stringWithFormat:@"Mintegral initialization failed: %@", exception.reason]];
            sInitializationStatus = 0;
            NSError *error = [CLXError errorWithCode:CLXErrorCodeAdapterInternalError
                                         description:@"Mintegral SDK initialization failed"];
            if (completion) completion(NO, error);
        }
    }
}

- (void)configurePrivacySettings:(MTGSDK *)mtgSDK {
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];

    // GDPR: Mintegral auto-reads IABTCF_TCString and IABTCF_gdprApplies from
    // NSUserDefaults. We do NOT override consentStatus here — doing so would
    // replace the granular TC-string-based consent with a blunt YES/NO.

    // CCPA: derive do-not-sell from IAB US Privacy String (1YNN format).
    // Index 2 == 'Y' means the user opted out of sale.
    NSString *usPrivacy = [defaults stringForKey:kIABUSPrivacy_String];
    if (usPrivacy.length >= 3) {
        unichar optOut = [usPrivacy characterAtIndex:2];
        if (optOut == 'Y') {
            mtgSDK.doNotTrackStatus = YES;
            [self.logger debug:@"Set doNotTrackStatus=YES (CCPA opt-out)"];
        } else {
            mtgSDK.doNotTrackStatus = NO;
            [self.logger debug:@"Set doNotTrackStatus=NO (no CCPA opt-out)"];
        }
    } else {
        mtgSDK.doNotTrackStatus = NO;
    }
}

/**
 * Set the channel code so that logs generated by Mintegral SDK can be attributed to CloudX.
 *
 * NOTE: The channel code must be obtained from Mintegral directly. Contact your Mintegral
 * account representative to request a unique channel code for CloudX.
 */
- (void)setChannelCode:(MTGSDK *)mtgSDK {
    if (kCloudXChannelCode.length == 0) {
        return;
    }

    @try {
        // setChannelFlag: is not exposed in MTGSDK's public headers, so we
        // invoke it dynamically with a respondsToSelector: guard.
        Class mintegralSdkClass = [mtgSDK class];
        SEL setChannelFlagSelector = NSSelectorFromString(@"setChannelFlag:");

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Warc-performSelector-leaks"
        if ([mintegralSdkClass respondsToSelector:setChannelFlagSelector]) {
            [mintegralSdkClass performSelector:setChannelFlagSelector withObject:kCloudXChannelCode];
        }
#pragma clang diagnostic pop
    }
    @catch (NSException *exception) {
        [self.logger warn:[NSString stringWithFormat:@"Failed to set channel code: %@", exception.reason]];
    }
}

@end
