platform :ios, '13.0'

target 'CloudXSwiftRemotePods' do
  use_frameworks! :linkage => :static

  pod 'CloudXCore', '~> 2.2.2'
  pod 'CloudXMetaAdapter', '~> 2.2.2'
  pod 'CloudXRenderer', '~> 2.2.2'
  pod 'CloudXVungleAdapter', '~> 2.2.2'
  pod 'CloudXInMobiAdapter', '~> 2.2.2'
  pod 'CloudXMintegralAdapter', '~> 2.2.2'

  target 'CloudXSwiftRemotePodsTests' do
    inherit! :search_paths
  end
  target 'CloudXSwiftRemotePodsUITests' do
  end
end
