//
//  CLXMetaBidTokenSource.h
//  CloudXMetaAdapter
//
//  Created by CLX on 2024-12-19.
//

#import <Foundation/Foundation.h>
#import <CloudXCore/CLXBidTokenSource.h>

NS_ASSUME_NONNULL_BEGIN

/**
 * Meta Audience Network bid token source for CloudX bidding integration.
 * 
 * The bid token is a cryptographically signed payload generated by Meta's SDK that contains:
 * - User targeting data (demographic, behavioral, interest signals)
 * - Device information (IDFA, device type, OS version, screen size)
 * - App context (bundle ID, app category, user engagement metrics)
 * - Privacy-compliant user identifiers and consent status
 * - Real-time bidding signals for ad auction optimization
 * 
 * This token is generated fresh for each auction request and allows Meta to:
 * 1. Participate in real-time bidding without exposing raw user data
 * 2. Calculate bid prices based on their proprietary targeting algorithms
 * 3. Ensure compliance with privacy regulations (GDPR, CCPA, etc.)
 * 4. Validate the authenticity of bid requests through cryptographic signatures
 * 
 * The token is passed to CloudX's auction server, which forwards it to Meta's
 * bidding endpoint during the OpenRTB auction process. Meta uses this token
 * to determine if they want to bid and at what price for the ad opportunity.
 */
@interface CLXMetaBidTokenSource : NSObject <CLXBidTokenSource>

/**
 * Shared instance for Meta bid token source.
 * @return Singleton instance
 */
+ (instancetype)sharedInstance;

/**
 * Factory method for CloudX adapter resolution system.
 * @return New instance of Meta bid token source
 */
+ (instancetype)createInstance;

@end

NS_ASSUME_NONNULL_END
